routes/web.php
<?php

use App\Http\Controllers\Controller;
use App\Http\Controllers\MatchController;
use App\Http\Controllers\TeamController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Get Data
Route::post('/getawayteam', [MatchController::class, 'awayteam'])->name('getawayteam');
Route::post('/gethometeamimages', [MatchController::class, 'homeimages'])->name('gethometeamimages');
Route::post('/getawayteamimages', [MatchController::class, 'awayimages'])->name('getawayteamimages');

// Home
Route::get('/', [Controller::class, 'index'])->name('home');

// Team
Route::prefix('team')->group(function() {
    Route::get('/', [TeamController::class, 'index'])->name('team.index');
    Route::get('/create', [TeamController::class, 'create'])->name('team.create');
    Route::get('/show/{id}', [TeamController::class, 'show'])->name('team.show');
    Route::get('/edit/{id}', [TeamController::class, 'edit'])->name('team.edit');
    Route::get('/destroy/{id}', [TeamController::class, 'destroy'])->name('team.destroy');
    Route::post('/store', [TeamController::class, 'store'])->name('team.store');
    Route::post('/update/{id}', [TeamController::class, 'update'])->name('team.update');
});

// Match
Route::prefix('match')->group(function() {
    Route::get('/', [MatchController::class, 'index'])->name('match.index');
    Route::get('/create', [MatchController::class, 'create'])->name('match.create');
    Route::get('/edit/{id}', [MatchController::class, 'edit'])->name('match.edit');
    Route::get('/show/{id}', [MatchController::class, 'show'])->name('match.show');
    Route::get('/status/{id}', [MatchController::class, 'status'])->name('match.status');
    Route::post('/store', [MatchController::class, 'store'])->name('match.store');
    Route::post('/update/{id}', [MatchController::class, 'update'])->name('match.update');
    Route::post('/finish/{id}', [MatchController::class, 'finish'])->name('match.finish');
    Route::post('/destroy/{id}', [MatchController::class, 'destroy'])->name('match.destroy');
});

app/Models/Pertandingan.php
<?php

namespace App\Models;

use App\Models\Team;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Pertandingan extends Model
{
    use HasFactory;

    protected $table = 'matches';
    protected $guarded = ['id'];

    public function home() {
        return $this->hasOne(Team::class, 'id', 'kandang');
    }

    public function away() {
        return $this->hasOne(Team::class, 'id', 'tandang');
    }

    public function getStatusTextAttribute()
    {
        if ($this->status == 0) {
            return '<span class="btn btn-danger fw-bold">Belum Selesai</span>';
        } else {
            return '<span class="btn btn-success fw-bold">Selesai</span>';
        }
    }

}

app/Http/Controllers/MatchController.php
<?php

namespace App\Http\Controllers;

use App\Models\Team;
use App\Models\Pertandingan;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class MatchController extends Controller
{
    public function index()
    {

        $curdate = Carbon::today();

        return view('match.index', [
            'title' => 'Jadwal Pertandingan',
            'matches_now' => Pertandingan::where('tanggal', '=', $curdate)->get(),
            'matches_all' => Pertandingan::all(),
        ]);
    }

    public function create()
    {
        return view('match.create', [
            'title' => 'Tambah Data Pertandingan',
            'homes' => Team::all()
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'kandang' => 'required',
            'tandang' => 'required',
            'tanggal' => 'required',
        ]);

        Pertandingan::create($data);

        if ($data) {
            return redirect()->route('match.index')->with('message', 'Data Pertandingan baru berhasil ditambahkan');
        } else {
            return redirect()->route('match.index')->with('message', 'Data Pertandingan baru gagal ditambahkan');
        }
    }

    public function show($id)
    {
        return view('match.show', [
            'title' => 'Pertandingan',
            'match' => Pertandingan::where('id', $id)->first(),
            'team' => Team::all(),
        ]);
    }

    public function edit($id)
    {
        return view('match.edit', [
            'title' => 'Ubah Data Pertandingan',
            'match' => Pertandingan::where('id', $id)->first(),
            'homes' => Team::all()
        ]);
    }

    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'kandang' => 'required',
            'tandang' => 'required',
            'tanggal' => 'required',
        ]);

        Pertandingan::where('id', $id)
            ->update($data);

        if ($data) {
            return redirect()->route('match.index')->with('message', 'Pertandingan berhasil diupdate');
        } else {
            return redirect()->route('match.index')->with('message', 'Pertandingan gagal diupdate');
        }
    }

    public function finish(Request $request, $id)
    {
        $data = $request->validate([
            'kandang'       => '',
            'tandang'       => '',
            'tanggal'       => '',
            'golKandang'    => '',
            'golTandang'    => '',
            'status'        => '',
        ]);

        Pertandingan::where('id', $id)
            ->update($data);

        if ($data) {
            return redirect()->route('match.index')->with('message', 'Pertandingan selesai');
        } else {
            return redirect()->route('match.index')->with('message', 'Pertandingan gagal');
        }
    }

    public function destroy($id)
    {
        $match = Pertandingan::where('id', $id)->first();

        Pertandingan::destroy($match->id);

        if ($match) {
            return redirect()->route('match.index')->with('message', 'Pertandingan berhasil dihapus');
        } else {
            return redirect()->route('match.index')->with('message', 'pertandingan gagal dihapus');
        }
    }

    public function homeimages(Request $request)
    {
        $homeTeam = $request->homeTeam;
        $team = Team::where('id', $homeTeam)->first();
        $option = asset($team->gambar);
        echo $option;
    }

    public function awayimages(Request $request)
    {
        $awayTeam = $request->awayTeam;
        $team = Team::where('id', $awayTeam)->first();
        $option = asset($team->gambar);
        echo $option;
    }

    public function awayteam(Request $request)
    {
        $tandang = DB::table('matches')->select('tandang');
        $kandang = DB::table('matches')->select('kandang');
        $home = $request->homeTeam;
        $awayTeams = Team::where('id', '!=', $home)->wherenotin('id', $tandang)
                ->orWhere('id', '!=', $home)->where($kandang, $home)->wherenotin('id', $tandang)->get();
        $option = '<option>Pilih Team Tandang</option>';
        foreach ($awayTeams as $awayTeam) {
            $option .= "<option value='$awayTeam->id'>$awayTeam->nama</option>";
        }
        echo $option;
    }

    public function status($id)
    {
        $match = Pertandingan::where('id', $id)->first();
        $match->status = $match->status == '0' ? '1' : $match->status = '0';
        $match->save();
        return redirect()->route('match.index')->withSuccess('Status pertandingan berhasil diubah');
    }
}

resources/views/match/create.blade.php
@extends('layouts.layouts')
@section('content')
    {{-- Teks --}}
    <div class="bg-light rounded-2">
        <p class="fw-bold text-center pb-3" style="font-size: 50px;">Tambah Data Pertandingan</p>
    </div>

    {{-- Previous --}}
    <div class="bg-light rounded-2 py-3">
        <div class="row">
            <div class="col-12">
                <a href="{{ url()->previous() }}" class="btn btn-icon bg-primary text-white ms-5">
                    <i class="fas fa-arrow-left"></i>
                    <p class="d-inline ms-2 fw-bold">Kembali</p>
                </a>
                <p class="pt-2 fw-bold ms-3 d-inline">
                    <a href="{{ route('home') }}" class="text-decoration-none">Home</a> /
                    <a href="{{ route('match.index') }}" class="text-decoration-none">Pertandingan</a> /
                    Create Pertandingan
                </p>
            </div>
        </div>
    </div>

    {{-- Form --}}
    <div class="card mt-3 px-3 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <p class="fw-bold text-primary fs-4">Input Data Pertandingan</p>
            </div>
            <div class="col-12 border border-dark rounded-3 px-2 py-2">
                <form action="{{ route('match.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="mb-3">
                                <label for="homeTeam" class="form-label">Home Team</label>
                                <select class="form-select" aria-label="Default select example" id="homeTeam" name="kandang">
                                    <option selected>Pilih Home Team</option>
                                    @foreach ($homes as $home)
                                        <option value="{{ $home->id }}">{{ $home->nama }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3 rounded-3 border text-center py-2 px-2">
                                <img src="{{ asset('image/mentah/dummy.png') }}" alt="" width="45%"
                                    class="rounded-3" id="homePreview">
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="mb-3">
                                <label for="formFile" class="form-label">Away Team</label>
                                <select class="form-select" aria-label="Default select example" id="awayTeam" name="tandang">
                                    <option selected>Pilih Home Team Terlebih Dahulu</option>
                                </select>
                            </div>
                            <div class="mb-3 rounded-3 border text-center py-2 px-2">
                                <img src="{{ asset('image/mentah/dummy.png') }}" alt="" width="45%"
                                    class="rounded-3" id="awayPreview">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mb-3">
                                <label for="" class="form-label">Tanggal Pertandingan</label>
                                <input type="date" class="form-control" name="tanggal">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="d-grid gap-2 mb-3 mt-3">
                                <button type="submit" class="btn btn-primary">Tambah Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $(function() {
                $('#homeTeam').on('change', function() {
                    let homeTeam = $('#homeTeam').val();
                    $.ajax({
                        type: "POST",
                        url: "{{ route('gethometeamimages') }}",
                        data: {
                            homeTeam: homeTeam
                        },
                        cache: false,
                        success: function(msg) {
                            $('#homePreview').attr("src", (msg));
                        },
                        error: function(data) {
                            console.log('error:', data);
                        },
                    });
                });
            });

            $(function() {
                $('#homeTeam').on('change', function() {
                    let homeTeam = $('#homeTeam').val();
                    console.log(homeTeam);
                    $.ajax({
                        type: "POST",
                        url: "{{ route('getawayteam') }}",
                        data: {
                            homeTeam: homeTeam
                        },
                        cache: false,
                        success: function(msg) {
                            $('#awayTeam').html(msg);
                        },
                        error: function(data) {
                            console.log('error:', data);
                        },
                    });
                });
            });

            $(function() {
                $('#awayTeam').on('change', function() {
                    let awayTeam = $('#awayTeam').val();
                    console.log(awayTeam);
                    $.ajax({
                        type: "POST",
                        url: "{{ route('getawayteamimages') }}",
                        data: {
                            awayTeam:awayTeam
                        },
                        cache: false,
                        success: function(msg) {
                            $('#awayPreview').attr("src", (msg));
                        },
                        error: function(data) {
                            console.log('error:', data);
                        },
                    });
                });
            });

        });
    </script>
@endsection

resources/views/match/edit.blade.php
@extends('layouts.layouts')
@section('content')
    {{-- Teks --}}
    <div class="bg-light rounded-2">
        <p class="fw-bold text-center pb-3" style="font-size: 50px;">Edit Data Pertandingan</p>
    </div>

    {{-- Previous --}}
    <div class="bg-light rounded-2 py-3">
        <div class="row">
            <div class="col-12">
                <a href="{{ url()->previous() }}" class="btn btn-icon bg-primary text-white ms-5">
                    <i class="fas fa-arrow-left"></i>
                    <p class="d-inline ms-2 fw-bold">Kembali</p>
                </a>
                <p class="pt-2 fw-bold ms-3 d-inline">
                    <a href="{{ route('home') }}" class="text-decoration-none">Home</a> /
                    <a href="{{ route('match.index') }}" class="text-decoration-none">Pertandingan</a> /
                    Edit Pertandingan
                </p>
            </div>
        </div>
    </div>

    {{-- Form --}}
    <div class="card mt-3 px-3 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <p class="fw-bold text-primary fs-4">Edit Data Pertandingan</p>
            </div>
            <div class="col-12 border border-dark rounded-3 px-2 py-2">
                <form action="{{ route('match.update', $match->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="mb-3">
                                <label for="homeTeam" class="form-label">Home Team</label>
                                <select class="form-select" aria-label="Default select example" id="homeTeam" name="kandang">
                                    <option selected>{{ $match->home->nama }}</option>
                                    @foreach ($homes as $home)
                                        <option value="{{ $home->id }}">{{ $home->nama }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3 rounded-3 border text-center py-2 px-2">
                                <img src="{{ asset($match->home->gambar) }}" alt="" width="45%"
                                    class="rounded-3" id="homePreview">
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="mb-3">
                                <label for="formFile" class="form-label">Away Team</label>
                                <select class="form-select" aria-label="Default select example" id="awayTeam" name="tandang">
                                    <option selected>{{ $match->away->nama }}</option>
                                </select>
                            </div>
                            <div class="mb-3 rounded-3 border text-center py-2 px-2">
                                <img src="{{ asset($match->away->gambar) }}" alt="" width="45%"
                                    class="rounded-3" id="awayPreview">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mb-3">
                                <label for="" class="form-label">Tanggal Pertandingan</label>
                                <input type="date" class="form-control" name="tanggal" value="{{ $match->tanggal }}">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="d-grid gap-2 mb-3 mt-3">
                                <button type="submit" class="btn btn-primary">Ubah Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $(function() {
                $('#homeTeam').on('change', function() {
                    let homeTeam = $('#homeTeam').val();
                    $.ajax({
                        type: "POST",
                        url: "{{ route('gethometeamimages') }}",
                        data: {
                            homeTeam: homeTeam
                        },
                        cache: false,
                        success: function(msg) {
                            $('#homePreview').attr("src", (msg));
                        },
                        error: function(data) {
                            console.log('error:', data);
                        },
                    });
                });
            });

            $(function() {
                $('#homeTeam').on('change', function() {
                    let homeTeam = $('#homeTeam').val();
                    console.log(homeTeam);
                    $.ajax({
                        type: "POST",
                        url: "{{ route('getawayteam') }}",
                        data: {
                            homeTeam: homeTeam
                        },
                        cache: false,
                        success: function(msg) {
                            $('#awayTeam').html(msg);
                        },
                        error: function(data) {
                            console.log('error:', data);
                        },
                    });
                });
            });

            $(function() {
                $('#awayTeam').on('change', function() {
                    let awayTeam = $('#awayTeam').val();
                    console.log(awayTeam);
                    $.ajax({
                        type: "POST",
                        url: "{{ route('getawayteamimages') }}",
                        data: {
                            awayTeam:awayTeam
                        },
                        cache: false,
                        success: function(msg) {
                            $('#awayPreview').attr("src", (msg));
                        },
                        error: function(data) {
                            console.log('error:', data);
                        },
                    });
                });
            });

        });
    </script>
@endsection

resources/views/match/index.blade.php
@extends('layouts.layouts')
@section('content')
    {{-- Teks --}}
    <div class="bg-light rounded-2">
        <p class="fw-bold text-center pb-3" style="font-size: 50px;">Pertandingan</p>
    </div>

    {{-- Previous --}}
    <div class="bg-light rounded-2 py-3">
        <div class="row">
            <div class="col-12">
                <a href="{{ url()->previous() }}" class="btn btn-icon bg-primary text-white ms-5">
                    <i class="fas fa-arrow-left"></i>
                    <p class="d-inline ms-2 fw-bold">Kembali</p>
                </a>
                <p class="pt-2 fw-bold ms-3 d-inline">
                    <a href="{{ route('home') }}" class="text-decoration-none">Home</a> / Match
                </p>
            </div>
        </div>
    </div>

    {{-- Alert --}}
    <div class="row mt-3">
        <div class="col-12">
            @if ($message = Session::get('message'))
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    <strong>{{ $message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
        </div>
    </div>

    {{-- Card Pertandingan Sekarang --}}
    @foreach ($matches_now as $match)
        <div class="card text-center mb-3">
            <div class="card-header">
                <p class="fw-bold">Pertandingan antara {{ $match->home->nama }} melawan {{ $match->away->nama }}</p>
            </div>
            <div class="card-body">
                <div class="row mb-3 mt-2">
                    <div class="col-5">
                        <p>Kandang</p>
                        <img src="{{ asset($match->home->gambar) }}" alt="{{ $match->home->nama }}" width="100px">
                        <p class="mt-2 fw-bold">{{ $match->golKandang ?? 0 }}</p>
                    </div>
                    <div class="col-2">
                        <p class="fs-4 fw-bold" style="padding-top: 50px">VS</p>
                    </div>
                    <div class="col-5">
                        <p>Tandang</p>
                        <img src="{{ asset($match->away->gambar) }}" alt="{{ $match->away->nama }}" width="100px">
                        <p class="mt-2 fw-bold">{{ $match->golKandang ?? 0 }}</p>
                    </div>
                </div>
                @if ($match->status == 0)
                    <a href="{{ route('match.show', $match->id) }}" class="btn btn-primary mb-3 mt-2">Menuju
                        Pertandingan!</a>
                @else
                    <a class="btn btn-success mb-3 mt-2 fw-bold">Pertandingan selesai!</a>
                @endif
            </div>
            <div class="card-footer text-body-secondary">
                <small class="text-muted">{{ $match->tanggal }}</small>
            </div>
        </div>
    @endforeach

    {{-- Datatables Pertandingan --}}
    <div class="card container mt-3 py-3">
        <div class="col-12">
            <p class="fw-bold fs-5 text-center text-primary">
                Jadwal Dan Status Pertandingan
            </p>
        </div>
        <div class="col-12 border border-dark p-3 rounded-3">
            <table id="example" class="table table-striped" style="width:100%;">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Tanggal Pertandingan</th>
                        <th>Team Home</th>
                        <th>Team Away</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($matches_all as $match)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $match->tanggal }}</td>
                            <td>{{ $match->home->nama }}</td>
                            <td>{{ $match->away->nama }}</td>
                            <td>
                                @if ($match->status == 0)
                                    <a href="{{ route('match.status', ['id' => $match->id]) }}">{!! $match->status_text !!}</a>
                                @else
                                    <a>{!! $match->status_text !!}</a>
                                @endif
                            </td>
                            @if ($match->status == 0)
                                <td>
                                    <div class="row">
                                        <div class="col-12 col-md-6 mb-1">
                                            <div class="d-grid gap-2">
                                                <a href="{{ route('match.edit', $match->id) }}"
                                                    class="btn btn-warning px-5 text-white fw-bold">Ubah</a>
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-6 mb-1">
                                            <div class="d-grid gap-2">
                                                <form action="{{ route('match.destroy', $match->id) }}" method="post">
                                                    @csrf
                                                    <button type="submit"
                                                        class="btn btn-danger px-5 fw-bold">Hapus</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            @else
                                <td>
                                    <div class="d-grid gap-2">
                                        <button class="btn btn-primary fw-bold">Pertandingan Selesai</button>
                                    </div>
                                </td>
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    {{-- Create Pertandingan --}}
    <div class="card mt-3 p-2">
        <div class="row">
            <div class="col-12">
                <div class="d-grid gap-2">
                    <a href="{{ route('match.create') }}" class="btn btn-primary">
                        Buat Pertandingan
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/match/show.blade.php
@extends('layouts.layouts')
@section('content')
    {{-- Teks --}}
    <div class="bg-light rounded-2">
        <p class="fw-bold text-center pb-3" style="font-size: 50px;">Tambah Data Pertandingan</p>
    </div>

    {{-- Previous --}}
    <div class="bg-light rounded-2 py-3">
        <div class="row">
            <div class="col-12">
                <a href="{{ url()->previous() }}" class="btn btn-icon bg-primary text-white ms-5">
                    <i class="fas fa-arrow-left"></i>
                    <p class="d-inline ms-2 fw-bold">Kembali</p>
                </a>
                <p class="pt-2 fw-bold ms-3 d-inline">
                    <a href="{{ route('home') }}" class="text-decoration-none">Home</a> /
                    <a href="{{ route('match.index') }}" class="text-decoration-none">Pertandingan</a> /
                    Match
                </p>
            </div>
        </div>
    </div>

    {{-- Card Match --}}
    <div class="card mt-3">
        <div class="row">
            <div class="col-12">
                <p class="text-primary fs-3 fw-bold text-center mt-2">
                    {{ $match->home->nama }} vs {{ $match->away->nama }}
                </p>
            </div>
            <div class="col-12">
                <form action="{{ route('match.finish', $match->id) }}" method="post" enctype="multipart/form-data" class="border border-dark rounded-3 mx-5 mb-5">
                    @csrf
                    <div class="row text-center my-3">
                        <input type="hidden" name="status" value="1">
                        <div class="col-5">
                            <p>Kandang</p>
                            <input type="hidden" name="kandang" id="" value="{{ $match->kandang }}">
                            <img src="{{ asset($match->home->gambar) }}" alt="{{ $match->home->nama }}" width="100px">
                            <input type="text" class="mt-2 fw-bold d-block mx-auto text-center border-0"
                                value="{{ $match->golKandang ?? 0 }}" name="golKandang"
                                style="resize:horizontal; width:20px">
                            <p>ubah skor disini</p>
                        </div>
                        <div class="col-2">
                            <p class="fs-4 fw-bold" style="padding-top: 50px">VS</p>
                        </div>
                        <div class="col-5">
                            <p>Tandang</p>
                            <input type="hidden" name="tandang" id="" value="{{ $match->tandang }}">
                            <img src="{{ asset($match->away->gambar) }}" alt="{{ $match->away->nama }}" width="100px">
                            <input type="text" class="mt-2 fw-bold d-block mx-auto text-center border-0"
                                value="{{ $match->golTandang ?? 0 }}" name="golTandang"
                                style="resize:horizontal; width:20px">
                            <p>ubah skor disini</p>
                        </div>
                        <div class="col-12 px-5 mt-3">
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary fw-bold">
                                    Selesaikan Pertandingan!
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection